
name: PHP Code Analysis

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  php-l:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['5.6']
    steps:
     - name: Install PHP 5.6
       uses: shivammathur/setup-php@v2
       with:
         php-version: ${{ matrix.php-versions }}
         extensions: intl #optional
         ini-values: "post_max_size=256M" #optional
       
     - run: mkdir plugin-opencart3
     - uses: actions/checkout@v2 
       with: 
         path: plugin-opencart3
      
     - name: Run php5.6 linter
       run: |
         find . -path ./vendor -prune -o -type f -name '*.php' ! -name '*twig.php' -print0 | xargs -0 -n1 -P$(nproc) php5.6 -l -n | (! grep -v 'No syntax errors detected')
       working-directory: plugin-opencart3
